export enum StorageErrorCode {
	INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
	METADATA_VALIDATION_ERROR = "METADATA_VALIDATION_ERROR",
	NETWORK_ERROR = "NETWORK_ERROR",
	UNKNOWN_ERROR = "UNKNOWN_ERROR",
	INVALID_FILE_INFO = "INVALID_FILE_INFO",
}
